# -*- coding: utf-8 -*-
"""PDS_dep_jobbert_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1en8ujAMS7s7IS9jx4c1d1la128H4pDHp
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)
import evaluate, torch, json
from google.colab import drive  # Colab-spezifisch

# Drive mounten (einmalig)
drive.mount('/content/drive')

# =========================================================
# 1. GEMERGTE CSV laden (FULL Dataset!)
# =========================================================
train_df = pd.read_csv("/content/drive/MyDrive/PDS_Snapaddy/combined_english.csv")  # Deine gemergte!
train_df = train_df[["text_en", "label"]].dropna().rename(columns={"text_en": "text"})

# Other entfernen (falls vorhanden)
train_df = train_df[train_df["label"] != "Other"].reset_index(drop=True)

print("FULL Train labels (7761 Samples):\n", train_df["label"].value_counts())

# =========================================================
# 2. Weighted Classes (automatisch berechnet!)
# =========================================================
label_encoder = LabelEncoder()
train_df["label_id"] = label_encoder.fit_transform(train_df["label"])
num_labels = train_df["label_id"].nunique()

# Class weights: Inverse Frequency (sklearn-style)
class_counts = train_df["label_id"].value_counts().sort_index()
total_samples = len(train_df)
class_weights = total_samples / (num_labels * class_counts)
class_weights = torch.tensor(class_weights.values, dtype=torch.float).to("cuda" if torch.cuda.is_available() else "cpu")

print("Labels:", list(label_encoder.classes_))
print("Class Weights:", class_weights.tolist())

# =========================================================
# 3. HF-Datasets (FULL → 80/20 Split)
# =========================================================
def to_hf_dataset(df_, text_col="text", label_col="label_id"):
    return Dataset.from_pandas(
        df_[[text_col, label_col]].rename(columns={text_col: "text", label_col: "label"})
    )

full_dataset = to_hf_dataset(train_df)
train_dataset = full_dataset.train_test_split(test_size=0.2, seed=42)["train"]  # 6208 Train
val_dataset   = full_dataset.train_test_split(test_size=0.2, seed=42)["test"]   # 1553 Val

print("Train/Val Split:", len(train_dataset), len(val_dataset))

# =========================================================
# 4. Tokenizer & Model
# =========================================================
MODEL_NAME = "TechWolf/JobBERT-v3"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def tokenize_function(batch):
    return tokenizer(
        batch["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

train_dataset = train_dataset.map(tokenize_function, batched=True)
val_dataset   = val_dataset.map(tokenize_function, batched=True)

cols = ["input_ids", "attention_mask", "label"]
train_dataset.set_format(type="torch", columns=cols)
val_dataset.set_format(type="torch", columns=cols)

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=num_labels
)

# =========================================================
# 5. Custom Trainer mit Weighted Loss!
# =========================================================
accuracy = evaluate.load("accuracy")
f1 = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy.compute(predictions=preds, references=labels)["accuracy"],
        "f1_macro": f1.compute(predictions=preds, references=labels, average="macro")["f1"],
    }
class_weights_global = class_weights

class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits
        loss_fct = torch.nn.CrossEntropyLoss(weight=class_weights_global.to(logits.device))
        loss = loss_fct(logits.view(-1, logits.shape[-1]), labels.view(-1))
        return (loss, outputs) if kwargs.get('return_outputs') else loss

save_dir = "/content/drive/MyDrive/PDS_Snapaddy/models/jobbertv3_department_FULL_weighted"

training_args = TrainingArguments(
    output_dir=save_dir,
    do_train=True,
    do_eval=True,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    weight_decay=0.01,
    logging_steps=50,
    eval_steps=500,      # Eval alle 500 steps
    save_steps=500,      # Save alle 500 steps
    eval_strategy="steps",  # ← FIX!
    save_strategy="steps",  # ← Match!
    fp16=torch.cuda.is_available(),
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    greater_is_better=True,
)

trainer = WeightedTrainer(
    model=model,
    args=training_args,  # Mit eval_strategy="steps" fix!
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
)

# =========================================================
# 6. Train & Eval
# =========================================================
trainer.train()
metrics_val = trainer.evaluate()
print("Val-Metriken:", metrics_val)

# =========================================================
# 7. Speichern
# =========================================================
trainer.save_model(save_dir)
tokenizer.save_pretrained(save_dir)

label_encoder_dict = {
    "classes": list(label_encoder.classes_),
    "mapping": {int(i): cls for i, cls in enumerate(label_encoder.classes_)},
    "class_weights": class_weights.cpu().tolist()  # Weights mit speichern!
}
with open(f"{save_dir}/label_encoder.json", "w", encoding="utf-8") as f:
    json.dump(label_encoder_dict, f, indent=2, ensure_ascii=False)

print("✅ Fertig! FULL Weighted JobBERT in", save_dir)
print("Val Accuracy:", metrics_val["eval_accuracy"])
print("Val F1-macro:", metrics_val["eval_f1_macro"])